#pragma config(Motor,  port2,           A,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           B,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           C,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (true) {
		motor[A] = 20;
		motor[B] = 20;
		motor[C] = -20;
	}

}
