#pragma config(Motor,  port2,           TR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           TL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while (true) {
        int forward = vexRT[Ch3]; // left joystick Y
				int turn    = vexRT[Ch1]; // right joystick X
        //motor[TR] = forward;
        motor[TL] = -forward-turn;
        motor[BR] = forward-turn;
        motor[BL] = -forward-turn;

    }
}
