#pragma config(Motor,  port2,           TR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           TL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           H,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           INTAKE,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (true) {
		int vertical = vexRT[Ch3]; // left joystick Y
		int horizontal = vexRT[Ch4]; // left joystick X
	  int turn = vexRT[Ch1]*(-0.8); // right joystick X

	  motor[TR] = vertical+turn;
	  motor[TL] = -vertical+turn;
	  motor[BR] = vertical+turn;
	  motor[BL] = -vertical+turn;
	  motor[H] = horizontal;
	  if(vexRT[Btn7R] == 1){
	  	motor[INTAKE] = 127;
		} else if (vexRT[Btn7D] == 1){
	  	motor[INTAKE] = -127;
		} else {
			motor[INTAKE] = 0;
		}
	}
}
